"""
TradeFlow — MACD Strategy
Generates BUY/SELL signals based on MACD line crossing the Signal line.
"""

from __future__ import annotations

import logging
from typing import Any

import pandas as pd

from app.strategies.base import BaseStrategy, Signal

logger = logging.getLogger(__name__)


class MacdStrategy(BaseStrategy):
    """
    MACD Signal Line Crossover Strategy.

    Logic:
        - BUY  when MACD line crosses ABOVE the signal line (bullish momentum).
        - SELL when MACD line crosses BELOW the signal line (bearish momentum).
        - HOLD otherwise.

    Requires DataFrame to contain MACD columns generated by pandas_ta:
        - MACD_{fast}_{slow}_{signal}
        - MACDs_{fast}_{slow}_{signal}
    Use app.data.indicators.add_macd() to enrich the DataFrame before simulation.
    """

    def __init__(self, fast: int = 12, slow: int = 26, signal: int = 9) -> None:
        """
        Initialize strategy with configurable MACD periods.

        Args:
            fast: Fast EMA period (default: 12).
            slow: Slow EMA period (default: 26).
            signal: Signal EMA period (default: 9).
        """
        self._fast = fast
        self._slow = slow
        self._signal = signal

        # pandas_ta column naming convention
        self._macd_col = f"MACD_{fast}_{slow}_{signal}"
        self._signal_col = f"MACDs_{fast}_{slow}_{signal}"

    @property
    def name(self) -> str:
        return f"MACD ({self._fast}/{self._slow}/{self._signal})"

    def generate_signal(self, df: pd.DataFrame, current_idx: int) -> tuple[Signal, str]:
        """
        Evaluate MACD crossover at the given bar index.

        Args:
            df: OHLCV DataFrame with MACD columns from pandas_ta.
            current_idx: Current bar index (0-based).

        Returns:
            Tuple of (Signal, reason_str).
        """
        if current_idx < 1:
            return Signal.HOLD, ""

        if self._macd_col not in df.columns or self._signal_col not in df.columns:
            logger.warning(
                "Missing MACD columns '%s' or '%s'. Run add_macd() first.",
                self._macd_col,
                self._signal_col,
            )
            return Signal.HOLD, f"Colonnes MACD manquantes"

        macd_now = df[self._macd_col].iloc[current_idx]
        macd_prev = df[self._macd_col].iloc[current_idx - 1]
        signal_now = df[self._signal_col].iloc[current_idx]
        signal_prev = df[self._signal_col].iloc[current_idx - 1]

        if any(pd.isna(v) for v in [macd_now, macd_prev, signal_now, signal_prev]):
            return Signal.HOLD, ""

        # MACD crosses above signal line → BUY
        if macd_prev <= signal_prev and macd_now > signal_now:
            reason = (
                f"MACD haussier : ligne MACD ({macd_now:.4f}) a croisé au-dessus de "
                f"la ligne signal ({signal_now:.4f}) — élan acheteur"
            )
            logger.debug("BUY signal at idx=%d (MACD crossover up, MACD=%.4f)", current_idx, macd_now)
            return Signal.BUY, reason

        # MACD crosses below signal line → SELL
        if macd_prev >= signal_prev and macd_now < signal_now:
            reason = (
                f"MACD baissier : ligne MACD ({macd_now:.4f}) a croisé en-dessous de "
                f"la ligne signal ({signal_now:.4f}) — élan vendeur"
            )
            logger.debug("SELL signal at idx=%d (MACD crossover down, MACD=%.4f)", current_idx, macd_now)
            return Signal.SELL, reason

        return Signal.HOLD, ""

    def get_params(self) -> dict[str, Any]:
        return {
            "fast": self._fast,
            "slow": self._slow,
            "signal": self._signal,
        }
